[book]
title = "블로그 생성기를 만들면서 배우는 하스켈"
description = "하스켈을 배우기 위한 프로젝트 중심적 온라인 책"
authors = ["Gil Mizrahi"]
language = "ko"
multilingual = false
src = "src"
git-repository-url = "https://github.com/jbl428/learn-haskell-blog-generator"
git-repository-icon = "fa-github"

[output.html]
git-repository-url = "https://github.com/jbl428/learn-haskell-blog-generator"
git-repository-icon = "fa-github"

